### ISSUE TITLE
Can this TMR F4PGA example designs?

### ISSUE THREAD

**Issue by AEW2015** [byuccl/spydrnet-tmr#18]
I would like to TMR the various example designs in this repo:
https://github.com/chipsalliance/f4pga-examples

Is the current guide sufficient enough?

**Comment by jacobdbrown4** [comment]
Yes, the guide should be sufficient to TMR example design from f4pga examples.

**Comment by jacobdbrown4** [comment]
@AEW2015 have you had any issues? Can I close this issue?
